import { useEffect, useState } from "react"
import { approveApplication, assignPropertyOwner, getApplications, getProperties, rejectApplication } from "@/domains/accommodations/api/admin"
import type { HotelierApplication } from "@/domains/auth/api/auth"
import type { HotelierHotel } from "@/domains/accommodations/api/hotelier"
import { ApiError } from "@/shared/lib/api-client"

export function Admin() {
    const [applications, setApplications] = useState<HotelierApplication[]>([])
    const [properties, setProperties] = useState<HotelierHotel[]>([])
    const [owners, setOwners] = useState<Record<string, string>>({})
    const [error, setError] = useState("")
    const load = async () => { try { const [requests, hotels] = await Promise.all([getApplications(), getProperties()]); setApplications(requests); setProperties(hotels); setOwners(Object.fromEntries(hotels.map(hotel => [hotel.hotelId, hotel.ownerUserId ?? ""]))) } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not load the admin workspace.") } }
    useEffect(() => { void load() }, [])
    async function reject(applicationId: string) { const reason = window.prompt("Why is this application being rejected?")?.trim(); if (!reason) return; try { await rejectApplication(applicationId, reason); await load() } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not reject application.") } }
    return <main className="stayora-container stayora-page"><p className="section-eyebrow">Admin workspace</p><h1 className="section-title mt-1">Platform moderation</h1>{error && <p role="alert" className="mt-4 text-sm text-error-600">{error}</p>}<section className="mt-6"><h2 className="font-heading text-2xl font-semibold text-primary-900">Pending hotelier applications</h2><div className="mt-4 grid gap-4">{applications.map(application => <article key={application.hotelierApplicationId} className="stayora-card"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><h3 className="font-semibold text-primary-900">{application.legalBusinessName}</h3><p className="text-sm text-text-secondary">{application.firstPropertyName} · {application.firstPropertyAddress}</p><p className="mt-2 text-sm">Registration: {application.registrationNumber} · {application.businessEmail}</p></div><div className="flex shrink-0 gap-2"><button onClick={() => void approveApplication(application.hotelierApplicationId).then(load).catch(cause => setError(cause instanceof ApiError ? cause.message : "Could not approve application."))} className="rounded-lg bg-primary-900 px-3 py-2 text-sm font-semibold text-white">Approve</button><button onClick={() => void reject(application.hotelierApplicationId)} className="rounded-lg border border-error-600 px-3 py-2 text-sm font-semibold text-error-600">Reject</button></div></div></article>)}{!applications.length && <p className="text-sm text-text-muted">There are no pending applications.</p>}</div></section><section className="mt-10"><h2 className="font-heading text-2xl font-semibold text-primary-900">Property management</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{properties.map(hotel => <article key={hotel.hotelId} className="stayora-card"><h3 className="font-semibold text-primary-900">{hotel.name}</h3><p className="text-sm text-text-secondary">{hotel.city}, {hotel.country}</p><label className="mt-4 block text-xs font-semibold uppercase tracking-wide text-text-muted">Owner user ID<input value={owners[hotel.hotelId] ?? ""} onChange={event => setOwners(current => ({ ...current, [hotel.hotelId]: event.target.value }))} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm normal-case" placeholder="User GUID" /></label><button onClick={() => void assignPropertyOwner(hotel.hotelId, owners[hotel.hotelId] || null).then(load).catch(cause => setError(cause instanceof ApiError ? cause.message : "Owner could not be assigned."))} className="mt-3 rounded-lg bg-primary-900 px-3 py-2 text-sm font-semibold text-white">Save owner</button></article>)}</div></section></main>
}
