services:
  hotel_booking_webapi:
    build:
      context: ./src/
      
    container_name: hotel_booking_webapi
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Database=hotel_booking;Username=postgres;Password=password
    ports:
      - "8080:8080"
        
    depends_on:
      - db
  db:
    image: postgres:17-alpine
    ports: 
        - "5433:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: hotel_booking
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:  
  db_data: