services:
  hotel_booking_webapi:
    build:
      context: .
      dockerfile: D
      
    ports:
      - "8080:8080"
        
    depends_on:
      - db
  db:
    image: postgres:latest
    ports: 
        - "5432:5432"
      