<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>DTO</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="DTOs\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common\BuildingBlocks\Application\Application.csproj" />
      <ProjectReference Include="..\Modules\HotelManagement\HotelManagement.Domain\HotelManagement.Domain.csproj" />
      <ProjectReference Include="..\Modules\RoomManagement\RoomManagement.Domain\RoomManagement.Domain.csproj" />
    </ItemGroup>

</Project>
