<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\PaymantManagement.Application\PaymantManagement.Application.csproj" />
      <ProjectReference Include="..\PaymantManagement.Infrastructure\PaymantManagement.Infrastructure.csproj" />
    </ItemGroup>

</Project>
