<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>

        
        <ProjectReference Include="..\..\Common\BuildingBlocks\Infrastructure\Infrastructure.csproj" />

        
        <ProjectReference Include="..\..\SharedKernel\SharedKernel.csproj" />
        <ProjectReference Include="..\..\Modules\BookingManagement\Booking.Application\Booking.Application.csproj" />
        <ProjectReference Include="..\..\Modules\BookingManagement\Booking.Domain\Booking.Domain.csproj" />
        <ProjectReference Include="..\..\Modules\BookingManagement\Booking.Infrastructure\Booking.Infrastructure.csproj" />
          <ProjectReference Include="..\..\Modules\Facilities\Facilities.Infrastructure\Facilities.Infrastructure.csproj" />
          <ProjectReference Include="..\..\Modules\HotelManagement\HotelManagement.Application\HotelManagement.Application.csproj" />
          <ProjectReference Include="..\..\Modules\HotelManagement\HotelManagement.Infrastructure\HotelManagement.Infrastructure.csproj" />
          <ProjectReference Include="..\..\Modules\RoomManagement\RoomManagement.Application\RoomManagement.Application.csproj" />
          <ProjectReference Include="..\..\Modules\RoomManagement\RoomManagement.Domain\RoomManagement.Domain.csproj" />
          <ProjectReference Include="..\..\Modules\RoomManagement\RoomManagement.Infrastructure\RoomManagement.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Composition\Room\" />
    </ItemGroup>

</Project>
