<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>RoomManagement.Application</RootNamespace>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\BuildingBlocks\Domain\Domain.csproj" />
      <ProjectReference Include="..\..\..\Common\BuildingBlocks\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
      <ProjectReference Include="..\..\BookingManagement\Booking.IntegrationEvents\Booking.IntegrationEvents.csproj" />
      <ProjectReference Include="..\..\HotelManagement\HotelManagement.IntegrationEvent\HotelManagement.IntegrationEvent.csproj" />
      <ProjectReference Include="..\..\PaymentManagement\PaymentManagement.IntegrationEvents\PaymentManagement.IntegrationEvents.csproj" />
      <ProjectReference Include="..\RoomManagement.Domain\RoomManagement.Domain.csproj" />
      <ProjectReference Include="..\RoomManagement.IntegrationEvent\RoomManagement.IntegrationEvent.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="EventHandlers\" />
    </ItemGroup>

</Project>
