<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>PaymentManagement.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\BookingManagement\Booking.IntegrationEvents\Booking.IntegrationEvents.csproj" />
      <ProjectReference Include="..\PaymentManagement.Domain\PaymentManagement.Domain.csproj" />
        <ProjectReference Include="..\PaymentManagement.IntegrationEvents\PaymentManagement.IntegrationEvents.csproj"/>
    </ItemGroup>

</Project>
