// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Users.Infrastructure;

#nullable disable

namespace Users.Infrastructure.Migrations;

[DbContext(typeof(UsersDbContext))]
partial class UsersDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Application.Outbox.OutboxMessage", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<string>("Data").IsRequired().HasColumnType("text");
            b.Property<DateTime>("OccurredOn").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ProcessedDate").HasColumnType("timestamp with time zone");
            b.Property<string>("Type").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.ToTable("OutboxMessages", "Identity");
        });

        modelBuilder.Entity("Infrastructure.Inbox.InboxMessage", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<string>("Data").IsRequired().HasColumnType("text");
            b.Property<DateTime>("OccurredOn").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ProcessedDate").HasColumnType("timestamp with time zone");
            b.Property<string>("Type").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.ToTable("InboxMessages", "Identity");
        });

        modelBuilder.Entity("Users.Domain.Entities.User", b =>
        {
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.Property<string>("Email").IsRequired().HasMaxLength(320).HasColumnType("character varying(320)");
            b.Property<string>("PasswordHash").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)");
            b.Property<string>("RefreshTokenHash").HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<DateTime?>("RefreshTokenExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<int>("Role").HasColumnType("integer");
            b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.HasKey("UserId");
            b.HasIndex("Email").IsUnique();
            b.HasIndex("Username").IsUnique();
            b.ComplexProperty<Dictionary<string, object>>("PersonalInfo", "Users.Domain.Entities.User.PersonalInfo#UserPersonalInfo", b1 =>
            {
                b1.IsRequired();
                b1.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("FirstName");
                b1.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("LastName");
                b1.Property<string>("PhoneNumber").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)").HasColumnName("PhoneNumber");
            });
            b.ToTable("Users", "Accounts");
        });
#pragma warning restore 612, 618
    }
}
