<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Accommodations.Application</RootNamespace>
    </PropertyGroup>

    

    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\BuildingBlocks\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.csproj" />
      <ProjectReference Include="..\..\Bookings\Bookings.IntegrationEvents\Bookings.IntegrationEvents.csproj" />
      <ProjectReference Include="..\..\Reviews\Reviews.IntegrationEvents\Reviews.IntegrationEvents.csproj" />
      <ProjectReference Include="..\Accommodations.Domain\Accommodations.Domain.csproj" />
      <ProjectReference Include="..\Accommodations.IntegrationEvent\Accommodations.IntegrationEvent.csproj" />
    </ItemGroup>

    

    <ItemGroup>
      <Folder Include="Command\Hotels\UpdateRating\" />
      <Folder Include="Events\EventNotifications\" />
      <Folder Include="Query\Pricing\" />
    </ItemGroup>
    
</Project>
