<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Notifications.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Common\BuildingBlocks\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\Notifications.Application\Notifications.Application.csproj" />
      <ProjectReference Include="..\Notifications.Domain\Notifications.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Configuration\Processing\Outbox\" />
    </ItemGroup>

</Project>
