// <auto-generated />
using System;
using System.Collections.Generic;
using Accommodations.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accommodations.Infrastructure.Migrations
{
    [DbContext(typeof(AccommodationsDbContext))]
    partial class AccommodationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accommodations.Domain.Entities.Hotels.Facility.HotelFacility", b =>
                {
                    b.Property<Guid>("HotelFacilityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("HotelFacilityId");

                    b.HasIndex("Category");

                    b.HasIndex("HotelId");

                    b.ToTable("HotelFacilities", "Accommodations");
                });

            modelBuilder.Entity("Accommodations.Domain.Entities.Hotels.Hotel", b =>
                {
                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("Rating");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "Accommodations.Domain.Entities.Hotels.Hotel.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Street");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("OperatingHours", "Accommodations.Domain.Entities.Hotels.Hotel.OperatingHours#OperatingHours", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly>("CheckIn")
                                .HasColumnType("time without time zone")
                                .HasColumnName("CheckIn");

                            b1.Property<TimeOnly>("CheckOut")
                                .HasColumnType("time without time zone")
                                .HasColumnName("CheckOut");
                        });

                    b.HasKey("HotelId");

                    b.HasIndex("Rating");

                    b.HasIndex("Status");

                    b.ToTable("Hotels", "Accommodations");
                });

            modelBuilder.Entity("Accommodations.Domain.Entities.Pricing.Pricing", b =>
                {
                    b.Property<Guid>("PricingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("Price", "Accommodations.Domain.Entities.Pricing.Pricing.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Price_Currency");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ValidDates", "Accommodations.Domain.Entities.Pricing.Pricing.ValidDates#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamptz")
                                .HasColumnName("ValidTo");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamptz")
                                .HasColumnName("ValidFrom");
                        });

                    b.HasKey("PricingId");

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomId", "IsActive");

                    b.ToTable("Pricing", "Accommodations");
                });

            modelBuilder.Entity("Accommodations.Domain.Entities.Rooms.Facility.RoomFacility", b =>
                {
                    b.Property<Guid>("RoomFacilityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("RoomFacilityId");

                    b.HasIndex("Category");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomFacilities", "Accommodations");
                });

            modelBuilder.Entity("Accommodations.Domain.Entities.Rooms.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Beds")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("DemandScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("BasePrice", "Accommodations.Domain.Entities.Rooms.Room.BasePrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("BasePrice_Currency");
                        });

                    b.HasKey("RoomId");

                    b.HasIndex("HotelId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Status");

                    b.HasIndex("HotelId", "RoomNumber")
                        .IsUnique();

                    b.ToTable("Rooms", "Accommodations");
                });

            modelBuilder.Entity("Application.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "Accommodations");
                });

            modelBuilder.Entity("Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InboxMessages", "Accommodations");
                });

            modelBuilder.Entity("Accommodations.Domain.Entities.Hotels.Facility.HotelFacility", b =>
                {
                    b.HasOne("Accommodations.Domain.Entities.Hotels.Hotel", null)
                        .WithMany("HotelFacilities")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accommodations.Domain.Entities.Hotels.Hotel", b =>
                {
                    b.OwnsOne("SharedKernel.ValueObjects.Money", "MinRoomPrice", b1 =>
                        {
                            b1.Property<Guid>("HotelId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MinRoomPrice_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("MinRoomPrice_Currency");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotels", "Accommodations");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.Navigation("MinRoomPrice");
                });

            modelBuilder.Entity("Accommodations.Domain.Entities.Rooms.Facility.RoomFacility", b =>
                {
                    b.HasOne("Accommodations.Domain.Entities.Rooms.Room", null)
                        .WithMany("Facilities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accommodations.Domain.Entities.Hotels.Hotel", b =>
                {
                    b.Navigation("HotelFacilities");
                });

            modelBuilder.Entity("Accommodations.Domain.Entities.Rooms.Room", b =>
                {
                    b.Navigation("Facilities");
                });
#pragma warning restore 612, 618
        }
    }
}
