import { useEffect, useMemo, useState } from "react"
import { Link, useNavigate, useParams } from "react-router-dom"
import { BedDouble, CalendarDays, Check, Clock3, DoorOpen, Plus, Settings2, Trash2, Users } from "lucide-react"
import { addHotelAmenity, addRoomAmenity, assignHotelOwner, checkIn, checkOut, createAddOn, getCalendar, getHotelierBookings, getHotelierHotels, getOverview, getSettings, removeHotelAmenity, removeRoomAmenity, setAddOnActive, type HotelierBooking, type HotelierCalendar, type HotelierHotel, type HotelierOverview, type HotelierSettings } from "@/api/hotelier"
import { ApiError } from "@/lib/api-client"
import { OccupancyCalendar } from "@/components/hotelier/OccupancyCalendar"

type Section = "overview" | "bookings" | "calendar" | "settings"
const sections: { id: Section; label: string; icon: typeof CalendarDays }[] = [{ id: "overview", label: "Overview", icon: Clock3 }, { id: "bookings", label: "Bookings", icon: CalendarDays }, { id: "calendar", label: "Rooms & calendar", icon: BedDouble }, { id: "settings", label: "Property settings", icon: Settings2 }]
const inputClass = "rounded-lg border bg-white px-3 py-2 text-sm text-primary-900 outline-none focus:border-gold-500"
const today = () => new Date().toISOString().slice(0, 10)

export function HotelierHotelList() {
    const [hotels, setHotels] = useState<HotelierHotel[]>([]); const [error, setError] = useState(""); const [owners, setOwners] = useState<Record<string, string>>({})
    const load = async () => { try { const data = await getHotelierHotels(); setHotels(data); setOwners(Object.fromEntries(data.map(hotel => [hotel.hotelId, hotel.ownerUserId ?? ""])))} catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not load hotels.") } }
    useEffect(() => { void load() }, [])
    return <main className="stayora-container stayora-page"><p className="section-eyebrow">Hotelier workspace</p><h1 className="section-title mt-1">Your properties</h1>{error && <p role="alert" className="mt-4 text-sm text-error-600">{error}</p>}<div className="mt-6 grid gap-4 md:grid-cols-2">{hotels.map(hotel => <article key={hotel.hotelId} className="stayora-card"><h2 className="font-heading text-xl font-semibold text-primary-900">{hotel.name}</h2><p className="text-sm text-text-secondary">{hotel.city}, {hotel.country}</p><Link to={`/hotelier/hotels/${hotel.hotelId}/overview`} className="mt-4 inline-block text-sm font-semibold text-primary-700">Open workspace →</Link><div className="mt-5 border-t pt-4"><label className="block text-xs font-semibold uppercase tracking-wide text-text-muted">Admin: assigned owner ID</label><div className="mt-2 flex gap-2"><input className={`${inputClass} min-w-0 flex-1`} value={owners[hotel.hotelId] ?? ""} onChange={event => setOwners(current => ({ ...current, [hotel.hotelId]: event.target.value }))} placeholder="User GUID" /><button onClick={() => void assignHotelOwner(hotel.hotelId, owners[hotel.hotelId] || null).then(load).catch(cause => setError(cause instanceof ApiError ? cause.message : "Owner could not be assigned."))} className="rounded-lg bg-primary-900 px-3 text-sm font-semibold text-white">Save</button></div></div></article>)}{!hotels.length && !error && <p className="text-sm text-text-muted">No assigned properties yet.</p>}</div></main>
}

export function HotelierDashboard() {
    const { hotelId, section: routeSection } = useParams<{ hotelId: string; section?: Section }>()
    const navigate = useNavigate()
    const section: Section = sections.some(item => item.id === routeSection) ? routeSection as Section : "overview"
    const [overview, setOverview] = useState<HotelierOverview | null>(null)
    const [bookings, setBookings] = useState<HotelierBooking[]>([])
    const [calendar, setCalendar] = useState<HotelierCalendar | null>(null)
    const [settings, setSettings] = useState<HotelierSettings | null>(null)
    const [calendarStart, setCalendarStart] = useState(today())
    const [status, setStatus] = useState("")
    const [roomId, setRoomId] = useState("")
    const [selected, setSelected] = useState<HotelierBooking | null>(null)
    const [error, setError] = useState("")
    const [loading, setLoading] = useState(false)

    const startDate = useMemo(() => new Date(`${calendarStart}T00:00:00`), [calendarStart])
    const load = async () => {
        if (!hotelId) return
        setLoading(true); setError("")
        try {
            if (section === "overview") setOverview(await getOverview(hotelId))
            if (section === "bookings") setBookings(await getHotelierBookings(hotelId, { status: status || undefined, roomId: roomId || undefined }))
            if (section === "calendar") setCalendar(await getCalendar(hotelId, calendarStart))
            if (section === "settings") setSettings(await getSettings(hotelId))
        } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not load hotelier data.") } finally { setLoading(false) }
    }
    useEffect(() => { void load() }, [hotelId, section, calendarStart, status, roomId])
    const changeStart = (offset: number) => { const date = new Date(`${calendarStart}T00:00:00`); date.setDate(date.getDate() + offset); setCalendarStart(date.toISOString().slice(0, 10)) }
    const runBookingAction = async (action: "checkin" | "checkout") => { if (!selected) return; try { if (action === "checkin") await checkIn(selected.id); else await checkOut(selected.id); setSelected(null); await load() } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Booking could not be updated.") } }

    if (!hotelId) return <main className="stayora-container stayora-page">Hotel is required.</main>
    return <main className="min-h-screen bg-bg-page"><div className="stayora-container py-6 md:py-10"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="section-eyebrow">Hotelier workspace</p><h1 className="mt-1 font-heading text-3xl font-semibold text-primary-900">Manage your property</h1></div><Link className="text-sm font-semibold text-primary-700 hover:text-gold-600" to={`/hotels/${hotelId}`}>View guest listing →</Link></div><nav aria-label="Hotelier sections" className="mb-6 flex gap-1 overflow-x-auto rounded-xl border bg-white p-1">{sections.map(item => { const Icon = item.icon; const active = item.id === section; return <button key={item.id} onClick={() => navigate(`/hotelier/hotels/${hotelId}/${item.id}`)} className={`inline-flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold ${active ? "bg-primary-900 text-white" : "text-text-secondary hover:bg-bg-muted"}`}><Icon size={16} />{item.label}</button> })}</nav>{error && <p role="alert" className="mb-4 rounded-lg bg-error-50 p-3 text-sm text-error-600">{error}</p>}{loading && <p className="rounded-xl border bg-white p-8 text-sm text-text-muted">Loading workspace…</p>}{!loading && section === "overview" && overview && <Overview data={overview} onBooking={setSelected} />}{!loading && section === "bookings" && <Bookings data={bookings} status={status} roomId={roomId} onStatus={setStatus} onRoom={setRoomId} onBooking={setSelected} />}{!loading && section === "calendar" && calendar && <><div className="mb-4 flex items-center gap-3"><label className="text-sm font-medium text-text-secondary">Jump to date <input className={`${inputClass} ml-2`} type="date" value={calendarStart} onChange={event => setCalendarStart(event.target.value)} /></label></div><OccupancyCalendar rooms={calendar.rooms} bookings={calendar.occupancy} start={startDate} onPrevious={() => changeStart(-14)} onNext={() => changeStart(14)} onBooking={setSelected} onRoom={(room) => navigate(`/hotelier/hotels/${hotelId}/settings#room-${room.roomId}`)} /></>}{!loading && section === "settings" && settings && <PropertySettings hotelId={hotelId} data={settings} onRefresh={load} />}</div>{selected && <BookingPanel booking={selected} onClose={() => setSelected(null)} onAction={runBookingAction} />}</main>
}

function Overview({ data, onBooking }: { data: HotelierOverview; onBooking: (booking: HotelierBooking) => void }) {
    const cards = [{ label: "Arrivals today", value: data.arrivalsToday, icon: DoorOpen }, { label: "Departures today", value: data.departuresToday, icon: CalendarDays }, { label: "Active stays", value: data.activeStays, icon: Users }, { label: "New bookings", value: data.newBookings, icon: Clock3 }]
    return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card => { const Icon = card.icon; return <article key={card.label} className="stayora-card p-5"><Icon size={20} className="text-gold-600" /><p className="mt-4 text-3xl font-semibold text-primary-900">{card.value}</p><p className="text-sm text-text-secondary">{card.label}</p></article> })}</div><section className="stayora-card"><h2 className="section-title">Next actions</h2><BookingRows items={data.nextActions} onBooking={onBooking} empty="Nothing needs attention right now." /></section></div>
}

function Bookings({ data, status, roomId, onStatus, onRoom, onBooking }: { data: HotelierBooking[]; status: string; roomId: string; onStatus: (value: string) => void; onRoom: (value: string) => void; onBooking: (booking: HotelierBooking) => void }) {
    return <section className="stayora-card"><div className="mb-5 flex flex-wrap gap-3"><select className={inputClass} value={status} onChange={event => onStatus(event.target.value)}><option value="">All statuses</option><option>Pending</option><option>Confirmed</option><option>CheckedIn</option><option>Completed</option><option>Cancelled</option></select><input className={inputClass} value={roomId} onChange={event => onRoom(event.target.value)} placeholder="Room ID" aria-label="Filter by room ID" /></div><BookingRows items={data} onBooking={onBooking} empty="No bookings match the filters." /></section>
}

function BookingRows({ items, onBooking, empty }: { items: HotelierBooking[]; onBooking: (booking: HotelierBooking) => void; empty: string }) {
    if (!items.length) return <p className="py-8 text-sm text-text-muted">{empty}</p>
    return <div className="overflow-x-auto"><table className="w-full min-w-[740px] text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-text-muted"><tr><th className="pb-3">Guest</th><th className="pb-3">Room</th><th className="pb-3">Stay</th><th className="pb-3">Total</th><th className="pb-3">Status</th></tr></thead><tbody>{items.map(item => <tr key={item.id} onClick={() => onBooking(item)} className="cursor-pointer border-b last:border-0 hover:bg-bg-warm"><td className="py-3 font-medium text-primary-900">{item.guestName}<span className="block text-xs font-normal text-text-muted">{item.guestEmail}</span></td><td className="py-3">{item.roomNumber || "—"}</td><td className="py-3">{formatDate(item.checkInDate)} – {formatDate(item.checkOutDate)}</td><td className="py-3">{item.totalPrice} {item.currency}</td><td className="py-3"><Status value={item.status} /></td></tr>)}</tbody></table></div>
}

function PropertySettings({ hotelId, data, onRefresh }: { hotelId: string; data: HotelierSettings; onRefresh: () => Promise<void> }) {
    const [amenity, setAmenity] = useState(""); const [roomAmenity, setRoomAmenity] = useState(""); const [activeRoom, setActiveRoom] = useState(data.rooms[0]?.roomId ?? ""); const [addOnName, setAddOnName] = useState(""); const [busy, setBusy] = useState(false)
    const commit = async (operation: () => Promise<unknown>) => { setBusy(true); try { await operation(); await onRefresh() } finally { setBusy(false) } }
    const selectedRoom = data.rooms.find(room => room.roomId === activeRoom)
    return <div className="grid gap-6 xl:grid-cols-2"><SettingsCard title="Hotel amenities"><AmenityList items={data.hotelFacilities} onRemove={id => commit(() => removeHotelAmenity(hotelId, id))} /><FormAdd value={amenity} onChange={setAmenity} disabled={busy} onAdd={() => { if (amenity.trim()) void commit(async () => { await addHotelAmenity(hotelId, amenity.trim()); setAmenity("") }) }} /></SettingsCard><SettingsCard title="Room amenities"><select className={`${inputClass} mb-3 w-full`} value={activeRoom} onChange={event => setActiveRoom(event.target.value)}>{data.rooms.map(room => <option key={room.roomId} value={room.roomId}>Room {room.roomNumber} · {room.type}</option>)}</select><AmenityList items={data.roomFacilities[activeRoom] ?? []} onRemove={id => { if (selectedRoom) void commit(() => removeRoomAmenity(hotelId, selectedRoom.roomId, id)) }} /><FormAdd value={roomAmenity} onChange={setRoomAmenity} disabled={busy || !selectedRoom} onAdd={() => { if (selectedRoom && roomAmenity.trim()) void commit(async () => { await addRoomAmenity(hotelId, selectedRoom.roomId, roomAmenity.trim()); setRoomAmenity("") }) }} /></SettingsCard><SettingsCard title="Add-ons"><div className="space-y-2">{data.addOns.map(addOn => <div key={addOn.hotelAddOnId} className="flex items-center justify-between gap-3 rounded-lg bg-bg-muted p-3 text-sm"><span><b>{addOn.name}</b> · {addOn.priceAmount} {addOn.priceCurrency}</span><button className="text-xs font-semibold text-primary-700" onClick={() => void commit(() => setAddOnActive(hotelId, addOn.hotelAddOnId, !addOn.isActive))}>{addOn.isActive ? "Deactivate" : "Activate"}</button></div>)}</div><FormAdd value={addOnName} onChange={setAddOnName} disabled={busy} placeholder="New add-on name" onAdd={() => { if (addOnName.trim()) void commit(async () => { await createAddOn(hotelId, { code: addOnName.toLowerCase().replaceAll(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""), name: addOnName.trim(), description: null, priceAmount: 0, priceCurrency: "EUR", pricingType: 1 }); setAddOnName("") }) }} /></SettingsCard><SettingsCard title="Policies"><p className="text-sm text-text-secondary">Policies remain available in the dedicated editor.</p><Link to={`/hotelier/hotels/${hotelId}/policies`} className="mt-4 inline-block text-sm font-semibold text-primary-700 hover:text-gold-600">Open policy editor →</Link></SettingsCard></div>
}

function SettingsCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="stayora-card"><h2 className="section-title mb-4">{title}</h2>{children}</section> }
function AmenityList({ items, onRemove }: { items: { id?: string; name: string }[]; onRemove: (id: string) => void }) { return <div className="mb-3 flex flex-wrap gap-2">{items.map(item => <span key={item.id ?? item.name} className="inline-flex items-center gap-1 rounded-full bg-gold-100 px-3 py-1 text-xs text-primary-800">{item.name}{item.id && <button onClick={() => onRemove(item.id!)} aria-label={`Remove ${item.name}`}><Trash2 size={13} /></button>}</span>)}{!items.length && <span className="text-sm text-text-muted">None added.</span>}</div> }
function FormAdd({ value, onChange, onAdd, disabled, placeholder = "Amenity name" }: { value: string; onChange: (value: string) => void; onAdd: () => void; disabled: boolean; placeholder?: string }) { return <div className="flex gap-2"><input className={`${inputClass} min-w-0 flex-1`} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} /><button disabled={disabled} onClick={onAdd} className="inline-flex items-center gap-1 rounded-lg bg-primary-900 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><Plus size={15} />Add</button></div> }
function BookingPanel({ booking, onClose, onAction }: { booking: HotelierBooking; onClose: () => void; onAction: (action: "checkin" | "checkout") => void }) { return <aside className="fixed inset-x-4 bottom-4 z-50 mx-auto max-w-md rounded-xl border bg-white p-5 shadow-lg"><div className="flex justify-between gap-4"><div><p className="section-eyebrow">Booking details</p><h2 className="font-heading text-xl font-semibold text-primary-900">{booking.guestName}</h2><p className="text-sm text-text-secondary">Room {booking.roomNumber || "—"} · {formatDate(booking.checkInDate)} – {formatDate(booking.checkOutDate)}</p></div><button onClick={onClose} className="text-sm text-text-muted">Close</button></div><div className="mt-4 flex gap-2">{booking.status === "Confirmed" && <button onClick={() => onAction("checkin")} className="inline-flex items-center gap-1 rounded-lg bg-primary-900 px-3 py-2 text-sm font-semibold text-white"><Check size={15} />Check in</button>}{booking.status === "CheckedIn" && <button onClick={() => onAction("checkout")} className="inline-flex items-center gap-1 rounded-lg bg-gold-500 px-3 py-2 text-sm font-semibold text-primary-900"><Check size={15} />Check out</button>}</div></aside> }
function Status({ value }: { value: string }) { return <span className={`rounded-full px-2 py-1 text-xs font-semibold ${value === "Pending" ? "bg-warning-100 text-warning-600" : value === "Confirmed" ? "bg-brand-blue-100 text-brand-blue-600" : value === "CheckedIn" ? "bg-success-100 text-success-600" : "bg-bg-muted text-text-secondary"}`}>{value}</span> }
function formatDate(value: string) { return new Date(value).toLocaleDateString("en-US", { month: "short", day: "numeric" }) }
