import { useEffect, useState, type FormEvent } from "react"
import { getHotelierApplication, getMe, submitHotelierApplication, type BusinessApplicationRequest, type HotelierApplication, type UserProfile } from "@/domains/auth/api/auth"
import { ApiError } from "@/shared/lib/api-client"

const emptyApplication: BusinessApplicationRequest = { legalBusinessName: "", registrationNumber: "", taxNumber: "", businessEmail: "", businessPhoneNumber: "", firstPropertyName: "", firstPropertyAddress: "" }

export function Account() {
    const [profile, setProfile] = useState<UserProfile | null>(null)
    const [application, setApplication] = useState<HotelierApplication | null>(null)
    const [form, setForm] = useState(emptyApplication)
    const [error, setError] = useState("")
    const [saving, setSaving] = useState(false)
    const load = async () => { try { const [me, request] = await Promise.all([getMe(), getHotelierApplication()]); setProfile(me); setApplication(request) } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not load your account.") } }
    useEffect(() => { void load() }, [])
    const update = <K extends keyof BusinessApplicationRequest>(key: K, value: BusinessApplicationRequest[K]) => setForm(current => ({ ...current, [key]: value }))
    async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); try { await submitHotelierApplication({ ...form, taxNumber: form.taxNumber || undefined }); await load() } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not submit your application.") } finally { setSaving(false) } }
    const canApply = !application || application.status === "Rejected"
    return <main className="stayora-container stayora-page"><p className="section-eyebrow">Guest workspace</p><h1 className="section-title mt-1">Account</h1>{error && <p role="alert" className="mt-4 text-sm text-error-600">{error}</p>}{profile && <section className="stayora-card mt-6"><h2 className="font-heading text-xl font-semibold text-primary-900">Your details</h2><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-text-muted">Name</dt><dd>{profile.firstName} {profile.lastName}</dd></div><div><dt className="text-text-muted">Email</dt><dd>{profile.email}</dd></div><div><dt className="text-text-muted">Phone</dt><dd>{profile.phoneNumber}</dd></div><div><dt className="text-text-muted">Workspace</dt><dd>{profile.role === "User" ? "Guest" : profile.role}</dd></div></dl></section>}<section className="stayora-card mt-6"><h2 className="font-heading text-xl font-semibold text-primary-900">Hotelier application</h2>{application && <div className="mt-3 text-sm"><p><span className="font-semibold">Status:</span> {application.status}</p><p className="mt-1 text-text-secondary">{application.legalBusinessName} · {application.firstPropertyName}</p>{application.status === "Pending" && <p className="mt-3 text-text-secondary">Your application is awaiting review.</p>}{application.status === "Approved" && <p className="mt-3 text-text-secondary">Approved. Sign out and sign back in to receive hotelier access.</p>}{application.status === "Rejected" && <p className="mt-3 text-error-600"><span className="font-semibold">Reason:</span> {application.rejectionReason}</p>}</div>}{canApply && <form onSubmit={submit} className="mt-5 border-t pt-5"><h3 className="font-semibold text-primary-900">{application ? "Submit a new application" : "Apply to list a property"}</h3><div className="grid gap-4 sm:grid-cols-2"><Field label="Legal business name" value={form.legalBusinessName} onChange={value => update("legalBusinessName", value)} /><Field label="Registration number" value={form.registrationNumber} onChange={value => update("registrationNumber", value)} /><Field label="Tax number (optional)" value={form.taxNumber ?? ""} onChange={value => update("taxNumber", value)} required={false} /><Field label="Business email" value={form.businessEmail} onChange={value => update("businessEmail", value)} type="email" /><Field label="Business phone" value={form.businessPhoneNumber} onChange={value => update("businessPhoneNumber", value)} /><Field label="First property name" value={form.firstPropertyName} onChange={value => update("firstPropertyName", value)} /></div><Field label="First property address" value={form.firstPropertyAddress} onChange={value => update("firstPropertyAddress", value)} /><button disabled={saving} className="mt-5 rounded-lg bg-primary-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Submitting…" : "Submit application"}</button></form>}</section></main>
}

function Field({ label, value, onChange, type = "text", required = true }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="mt-4 block text-sm font-medium text-primary-900">{label}<input required={required} type={type} value={value} onChange={event => onChange(event.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2" /></label> }
